name: joblisting
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  go_router: ^14.6.3
  dio: ^5.7.0
  gap: ^3.0.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  sign_in_button: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1
  app_bar_with_search_switch: ^1.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/job-search.png"
  adaptive_icon_background: "#ffffff"
flutter:
  uses-material-design: true
