// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ho3Qtl7c6SMObV5GVZSPmkxTiyhoODc',
    appId: '1:671979608570:android:4fd017a9c689de0c492c43',
    messagingSenderId: '671979608570',
    projectId: 'fir-login-a8e63',
    databaseURL: 'https://fir-login-a8e63-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-a8e63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdNs5FIxG6_RKTPCjkG2AvPMLHyn85WcM',
    appId: '1:671979608570:ios:4ba9a2253654cf91492c43',
    messagingSenderId: '671979608570',
    projectId: 'fir-login-a8e63',
    databaseURL: 'https://fir-login-a8e63-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-a8e63.appspot.com',
    androidClientId:
        '671979608570-u72p6qb247odkli917noi87pcntt6ipf.apps.googleusercontent.com',
    iosClientId:
        '671979608570-626pa34ceddmhd5b5m5caecvsvd7qdhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.joblisting',
  );
}
